---
output: 
    bookdown::pdf_document2:
        toc: false
bibliography: Demography.bib
biblio-style: "apalike"
fontsize: 12pt
---

# Background  

Demographic research lies at the nexus of social science research and shares much in common with other fields. The overlap between demography and other fields often puts it in a difficult place in terms of solidfying it's place as a unique field. This may be esepcially true in the current era of large scale data production where research concerning "populations" is used by a larger number of research fields. These large N studies allow for more detailed divisions and subpopulations within a particular population to be studied, making the distinction between demography and other fields more blurred. While one could imagine a scenario where this could drain demography of its standing while other fields take over the space it once occupied this seems not to bve the case. The expnasion of data has come alongside an expansion in those that  take a demographic mindset into their analysis and incoporate demographic methods into their respective fields of study. It may be because of this that we have seen a relative growth in the size of instutions in the United States that are associated with demographic research, while at the same time a collopsing down in the size and number of academic institutions that house a proper school of demography [@Xie2000]. In order to best summarize how we arrived at the current state of demography research I will discuss and review a brief series of papers that cover the history of demographic research in the 20 and 21st century, with particular attention to the development of the field in the United States.  

# Formal Demography and Population Studies  

It is likely impossible to find a credible account of the history of demography in the United States without acknowledging Hauser and Duncan 1959 piece _The Study of Population_. The work attempted to establish demography as a legitimate social science and the particular research domains for which the field holds a special claim to. Though the work spans nearly 900 pages the often most cited passage comes to us as the direct, albeit vauge, statement of what constitutes the field of demography. Hauser and Duncan state _Demography is the study of the size, territorial distribution, and composition of population, changes therein, and the components of such change._ While not stated specfifcally here the elements that constitute population changes in a society can be traced back to the fors of the demographic balancing equation, namely the increase contributed by births and the decreases attributed to death. If we subdivide our population into specific geographic areas then we must also consider how populations move in space and how these spaces may differentially experience births and deaths and thus, the particular focus that is placed on _territorial distribution_. How the age distribution of deaths, and the age of and number of children, predominately, woman have are "shaped", ie their age distributions, and how that shape changes are at the heart of what is now considered formal demography. On the other hand we have population process and social demography. This set of demography is more interested in the social drivers that alter the distributions of mortality, fertility, and migration. The distinction between the two fields has seen development of theoretical opposition happen in one field even if it was at the disnmay of the other, a topic that I will touch on further in this reprt.  

# The Demographic Transition and Mortality

Whether the distinction between these two fields is helpful or not it's seperation has helped shape the current state of the demographic field. Perhaps one of the most influential aspects from the formal demographic group has been the development of age-specfic profilles of mortality and feryility and their relationship to developmental change in what is known as the demographic transition. Briefly the demographic transition states that as a country develops in it's technologies and economic infrastructures it expexperiences a decline in it's child mortality and then in it total fertility rate which leads to a period in the disruption of the equilibrium of balancing forces, casuing an uptick in population [@Lee2003]. Chil mortality declines are often associated with advances in care but can also be due to greater and more egalitarian access to care, an increase in the social status of women, increased education of both men and women, as well as better overall access to reproductive health needs [@CALDWELL1990]. 

While the original theory was coined in the United States by demographer Warren Thompson around 1930, a number of subsequent articles have been written that expand on the timing, the population effect, and the applicability of the transition on a number of countries. One of the more discussed papers on the topic has been Caldwell's 1986 paper "Routes to Low Mortality in Developing Countries" [@Caldwell1986]. The paper uses the 1984 World Development Bank report in order to assess how both Infant Mortality Rate (IMR), the rate of death of persona under the age of 1, and Child Mortality Rate (CMR), the rate of death of persons under the age of 5, have varying countrying level differences and how those differences compare with over all period life expectency at birth, level of income, as well as some qualitative assessments of investment by a country into the health systems infrastructure of the state, especially in Costa Rica, Cuba, and Vietnam. His primary focus on the analysis was on developing countries, termed third world countries in the original text, and how they ranked on their child health indicators.

In Caldwell's analysis he placed a strong focus on the idea of economic expectation of health outcomes. Whether by intention or not, his focus on the parrallel's between econmic success and health outcomes helped to cement the role of economic theory into the demographic transition. This is not to say that economics role was not present before this paper, much of the demographic transition research was originally formulated based on increasing econmies within countries, however, the shear influence of this paper has led to the continued use of expectation of health outcomes conditional on economic success even in contemporary work. A prime example of this is the use of the Socio-demographic index (SDI) measure used by researchers such as those from the work of the Institute for Health Metrics and Evaluation (IHME) in their work measuring IMR and expectations of IMR at a country level [@Wang2012]. 

In his original work, Caldwell simply ranked countries based on their status for IMR/CMR and then by thier GNP. He payed special attention to countries who "performed" higher or lower than expected based on thier economic ranking using a critria of having a health ranking either 25 places above or below thier econmomic ranking respectively. Obviously, this measure was crude and ignored the qunatititave differences in both IMR and GNP, however, the focus on strong achievers allowed Caldwell to build a set of hypothesis of the drivers of child mortality reduction that arent necessarily tied to the wealth of a country. Of particular note is Caldwell's focus on the autonmy of woman, education and political systems, as well as the cultural attitudes that may drive health outcomes.  

While Caldwell's paper was without a doubt a huge step forward in the discussion of drivers of demographic change, it was met with many rebuttals and reflections from other demographers within the field. A particularly notweworthy revisitation to Caldwell's original piece was Randall Kuhn's 2010 article in Population and Development Review [@Kuhn2010]. Kuhn made particular care to revist the limitations of the original article that had been made by himself as well as other researchers since Caldwell's original publication. In particular he focused on the causal language that was used especiallly related to the impact that religion could play on child mortality outcomes. This was easily refuted in other work by making country comparisons for states that were not included in the original analysis. Nonetheless, the lasting influence of Caldwell's paper led Kuhn to run as similar analysis of countries this time using a perhaps  more indicative measure of person level economic standing, the purchasing power parity (ppp). The results led to some similar findings, countries that had high ppp but were primarily oil based economies still lagged behind in health standings related to IMR. The new updated rankings however found the relative lagging of health outcomes by country tend to change over time. This was especiialy true for Latin Americand and predominately Arabic countries [@Kuhn2010].

Despite this more careful attention to details Kuhn's article still places an extreme importance on economic success in the way that we frame health outcomes. Countries in Latin America who have political systems that are more socialist than here in the United States such as Cuba and Costa Rica are seen as exceptions despite both of these countries, as detailed in the paper, spending more on health care infrastructure. In addition the framework presented places a strong importance on average health outcomes and largeley neglects variation in health outcomes. This comes along with language that often reflects a causal nature, even though Kuhn himself was crtitcal of Caldwell's causal remarks, and calls into question when exactly a primary focus should be placed on shifting trends in means of population measures in relation to country level indicators, in econmics and beyond [@GregJ.Duncan2008]. 

A more pointed claim of the importance of econmics, especially in relation to public health efforts was founded in the so-called "McKeown Thesis" [@McKeown1972]. McKeown placed a strong importance on the roles of economic growth, rising living standards, and improved nutrition as the primary sources of most historical improvements in the health of developed nations and population growth. The article is often seen as downplaying the importance of public health's role inaltering population change and has been hit with many criticism's across the years. A series of papers commissioned by the American Journal of Public Health sought re-evaluate the original papers claims and rethink how public health and health systems effect health outcomes [@Szreter2002]  [@Colgrove2002] [@Link2002]. In addition a growing number of articles, including those that were written as responses to Caldwell, show that changes in the vaccination schedule and distribution and access to clean water can have a measurable effect omn the rate of child mortality, especially demonstarted in the declines in under five mortality in Latin American Countries [@Gonzalez-Pier2016] [@Kuhn2010][@Palloni1999][@SZRETER1988]. 

# Devloping Theory and Causal Modeling

Again this debate of the importance of changing country or state level indicators and best predicting changes in population structure, child mortality and fertility declines leading to population growth, brings up the question of what data we can use for making causal connections and adapting theory for drivers of population change. This discussion of theoretical drivers of change is much discussed [@Lee2003][@Preston1993][@Xie2000] and perhaps what most sets apart fromal demography from social demography and population sciences. While there is no doubt value in descriptive statistics and compositional analysis of change, what fuels these changes in different context is especially importaant not only for our own academic understanding but also because demography is inherently tied to policy and its implemenation [@Greenhalgh1996][@Tienda2002]. It is important then that we are crtitcal of the methodology that we use to test our assumptions of causal drivers of population change, but also be crtitcal of the climate that has historically created theories on population changes. 

As stated prior, the ways in which we approach causal claims in demography need to be done carefully. Demography concerns itself with changes at the population level, however, the often cited gold standard for making causal claims comes from the set up of a randomized control trial [@Moffitt2005]. While we may take studsies from psychology, biology, public health, and experimental sociology to help develop our theories, the kind of scale and data that demography deals with does not well lend itslef to these kibnds of tests. To refernce Hauser and Duncan again, one of the main interest of demographers is differnces in population by geograpghic space. The ways which we hypothesise space, the physical area that an individual resides in, and place, the conceptualized area that an individual occupies and its characteristics, are likely things that we could never ethically test in a randomized control style setting. Ways around this limitation have been discussed and examples of such include natural experiemnts, such as the Moving to Opportunity study which tested how individuals living in poverty who were nearly randomly assigned a new location withion a more developed neighborhood, twin studies, selecting individuals that match on all characteristics except some treartment effect, as well as other methodilogical approaches that allow for weighting of recieving treatment to be taken into account in the model such as in Marginal Structural Models [@Sampson2008].

In 2007 Bhrolchain and Dyson presented an article which attempeted to highlight some of the ways in which causal claims have been made in demography in the past and how they were either lacking in adequate testing of causality or could only be evaluated by the existence of previously purported theories [@Bhrolchain2007]. This is not to say that causal infernce is beyond the realm of population studies, but rather, we need to be careful in how we make causal claims and the dat that we use in order to do so. An overview of cauasality ansd how it main be assessed was well articulated by Moffitt in his 2005 article "Remarks on the analysis of causal relationships in population research" [@Moffitt2005]. Moffit highlights how intuition in tradional modeling approaches can lead to false claims of the importance of some variables on population process and again evokes the importance of theory, and in his own words intuition, must be used when considering causal relationships.

The history of demographic theories of change, however, should be considered within the context of its development. Unlike many other social sciences, demography did not become solidified as a social science until the early half of the 20th century. It's relatively late development and combined with its core bassed in descriptive statsitics have made it relatively young in terms of theoretical development. Nonetheless, the "modernist" theories that have become antiquated or at least more contested in other social science fields as other theoretical persepctives that challeged the western centric ecnomic and thecnological based theories have not been as pervasive in the field of demography. Authors such as Greenhalgh and Szreter have argued that the reason for this lack of development is the close ties between the development of the field of demography and the political agenda of developed western countries, primarily the United States [@Greenhalgh1996]. Even the founding of the Population Ascoiation of America (PAA) was constructed with the thought in mind of demographies role in economic and social planning related to fertility. In addition the expectation of other countries growths related to concerns of asian growth as well as countries that do not follow the western pattern of growth, see the African Exception, firmly center norms around western models. This line of reasonaning is notably absent of cultural and poltical differnces between countries that can drive differences in population growth.  

# Fertility Variation and Demography  

In addition to mortality changes demography is strongly concerned with fertility changes as well. The demographic transition closely relates these two factors together, however, the mechansims for declines should not be seen as causal unless one takes an extremely utilitarian approach to how individuals plan for their children. Perhaps one of the most attractive aspects of the demographic transition theory is its relative simplicity and ubiquity as it is applicable to all countries. However the degree to which the model is applicable depends strongly on the country. When no models are introduced, however, they often do not come as close to being comprehensive as the demographic theory model and often only describe the situation of a few countries. Demography pursists often favor the ability of a more general model that can be extrapolated to a large number of situations than one that is dependent on subtle context [@Hirschman1994].  

While many papers in the field of demography focus on the large social determinants of change related to demographic outcomes, it is often helpfult to limit the scope of reserach to the direct process that leads to changes. While no doubt culture [@Bongaarts2013], economics [@Easterlin1975], development [@Bryant2007], and ideational shifts [@Hirschman1994] play a role in the changes of fertility, the mechanisms by which these foces exhibit change are limited to much narrower range of proximate causes. Easterlin's 1975 article, An economic framework for fertility analysis, represents a response to the simple economic demand model and its criticisms that were present in the field at the time. He states that fertility rates are a function of three main factors, the threshold factor which places an upper limit on the maximum number of children possible, the demand for children which is dictated by economic, cultural, and social needs, and the means by/access to which pregnancy may be avoided. The model expands on previous notions of what influences differences in time and cultures of fertility rates while still providing a testable model by which the demographic transition could happen, although he is very vague in the way that he says that culture, society, and the economy do affect fertility. Three years later Bongaarts wrote on the importance of understanding the causal factors by which fertility is regulated and not just the social factors [@Bongaarts1978]. He places extreme importance on three categories of factors that mechanistically restrict fertility and claims that understanding of their relationship to fertility rates is a requirement in order to understand and test how social factors can lead to changes fertility via these mechanisms. 

While these artciles place a strong focus on the proximate measures of fertility changes, they bring to question where the the theoretical focus of demographic research should be placed. It is difficult to argue against Bongarts's claims that the rate limiting factors that lead to changes in fertility are not much beyond exposure factors, delibrate marital fertility control factors, and natural marital fertility factors. However, while Bongarts would later claim that his factors accounted for a large percentage of variation in follow up papers, the ability to assess how these factors change remains up for debate. For example, the introducation of braodened reproductive health care systems allows for the upatke of contraceptive use, yet, how much demand there is for contraceptive is still a function of other social forces and, depending on the payment and insurance structures of reprocuctive health in the country of concern, economic forces as well. These more "upstream", to use the language of the social determinants of health researchers, causes are more difficult to predict and build theoretical models of fertility change for, however, are essential for future research. For example, the aim of planning for future population growth is contigent on changes in fertility and building forecasts that include scenario's of culture shifts in a probabilistic manor, see [@Raftery2014a], would be immensly hepful from an institutional planning standpoint. 

# Ethnic, Racial, Gendered, and Geographic Differences In Demography

Up to this point much of the work that we have been describing has focused on change and theory as it is related to country level differnces of change. However, more and morre recent research has taken into account variation within countries and its role in creating small area population differences among subgroups. How this variation manifests under a single state often reflects differences in social status much researched by other fields and has been a more focused topic of demography since the late 80's, especially in the United States. When discussing variation within countries, conversations of social drivers of change are much more common. Much of the dialouge around socio-economic level differnces in fertility and mortality outcomes have looked at how culture attitudes and social status alter decision making patterns related to family planning. Perhaps no greater focus on demographic variation in the United States has been placed on the difference in black and white mortality and fertility outcomes.  

In Ruggles 1994, Ruggles gather US census data for years spanning from 1880 to 1980 in order to understand the history of the black white differences in family structures. At this point differences between black and white family structures in the United States had long been studied, and its consequences were actively being debated such in the, controversial, Moynihan report "The Negro Family: The Case For National Action". In the report Moynihan attributes the economic plight of the African Americans up until the 1960's to the family structure, that African Americans or more likely to be part of single family homes. Ruggles finds in his historical analysis that  although blacks have historically had a higher rate of fragmented households, the prevalence of fragmented families was much smaller in the past for both black and whites and the absolute difference between the two was much smaller in the 19th century [@S1994]. Tolnay expands on the historical differences between black and white family structures by analyzing the differences within the black community in the north and south during the era of great migration out of the south. Tolnay finds that it is unlikely that southerners brought with them a culture of fragmented households and that the differences, at least to some extent, were generated within the north, possibly due to social factors (possibly reversing the causality asserted in the Moynihan report) [@Tolnay1997]. These articles both lend evidence to the notion that socioeconomic status (SES), plays an important role in health inequalities, a sentiment that would be echoed more causaly in future literature [@Phelan2010, @Singh-Manoux2005].

All of these papers comment on the importance of propagation of factors, both social and cultural, that start at eraly life but further literature expand's on this notion by adding a biological component of poor health accumulation in the form of allostatic load, a term coined by neuro-endocronlogist Bruce McEwen. Though strictly attributing poor health outcomes or any population dynamic to any single one of these factors is difficult, namely because of how co-linear they are, it is imprtant to understand all three factors when considering demographic variation. One of the earliest papers in demographic research that described the lasting effects of negative early life conditions was Hayward and Gorman's "The Long Arm of Childhood: The Influence of Early-Life Social Conditions on Men's Mortality" [@Hayward2004]. The analysis fo8und that even after conditioning on changes in adult lifestyle, that childhood characteristics still played an important factor in describing differentials in moratality outcomes. The author's concluding statements placed a strong focus on the idea that social welfare policies should be particularly focused on  childhood outcomes, not only for the potential causal pathways that may lead a child to better health but also beacaue of the potential permanent biological systems that may be damaged because of early life stress. 



\newpage

# References  
